
package me.heldplayer.mods.Smartestone.util;

public final class Const {

    public static final int CRAFTINGCHEST_INV_SIZE = 22;
    public static final int CRAFTINGCHEST_CRAFTMATRIX_INV_SIZE = 9;
    public static final int CRAFTINGCHEST_PLANS_INV_SIZE = 6;
    public static final int CRAFTINGCHEST_CRAFTRESULT_SLOT = CRAFTINGCHEST_INV_SIZE + CRAFTINGCHEST_CRAFTMATRIX_INV_SIZE;
    public static final int CRAFTINGCHEST_TOTAL_INV_SIZE = CRAFTINGCHEST_CRAFTRESULT_SLOT + CRAFTINGCHEST_PLANS_INV_SIZE + 1;

    public static final int INDUCTIONISHFURNACE_INV_SIZE = 9;
    public static final int INDUCTIONISHFURNACE_INPUT_SLOT = INDUCTIONISHFURNACE_INV_SIZE;
    public static final int INDUCTIONISHFURNACE_FUEL_SLOT = INDUCTIONISHFURNACE_INPUT_SLOT + 1;
    public static final int INDUCTIONISHFURNACE_OUTPUT_SLOT = INDUCTIONISHFURNACE_FUEL_SLOT + 1;
    public static final int INDUCTIONISHFURNACE_TOTAL_INV_SIZE = INDUCTIONISHFURNACE_OUTPUT_SLOT + 1;

}
